"use client"
import "./globals.css";
import Navbar from "@/components/items/navbar/Nav";
import Footer from "@/components/items/footer/footer";
import React,{useEffect} from 'react'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import AOS from 'aos';
import 'aos/dist/aos.css';
import  {store}  from '../Features/store';
import {Provider, useSelector} from 'react-redux';
import ThemeChooser from "@/components/items/theme/theme";
import ThemeMaker from "@/components/items/theme/ThemeMaker";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  
  useEffect(() => {
    AOS.init({
      duration: 800,
      
    })
  }, [])
 
 
  return (
      <Provider store={store}>
    <html lang="en">
      <body className="">
<ThemeMaker>


       
        <Navbar/>
        <div className="relative top-36 overflow-hidden">
       

        {children}
        <ToastContainer />

        
        <ThemeChooser />
        <Footer/>


        </div>
        </ThemeMaker>
        </body>
    </html>
        </Provider>
  );
}
